export const CURRENCY_OPTIONS_LOAD_REQUEST = "CURRENCY_OPTIONS_LOAD_REQUEST";
export const CURRENCY_OPTIONS_LOAD_FAILED = "CURRENCY_OPTIONS_LOAD_FAILED";
export const CURRENCY_OPTIONS_LOAD_SUCCESS = "CURRENCY_OPTIONS_LOAD_SUCCESS";
