export const BITCOIN_PRICE_POINTS_LOAD_REQUEST =
  "BITCOIN_PRICE_POINTS_LOAD_REQUEST";
export const BITCOIN_PRICE_POINTS_LOAD_FAILED =
  "BITCOIN_PRICE_POINTS_LOAD_FAILED";
export const BITCOIN_PRICE_POINTS_LOAD_SUCCESS =
  "BITCOIN_PRICE_POINTS_LOAD_SUCCESS";
